export const TAGS_BY_CATEGORY: Record<string, string[]> = {
  "Science & Technology": [
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "engineering",
    "technology",
    "robotics",
    "dataScience",
  ],
  "Ideas & Innovation": [
    "startup",
    "entrepreneurship",
    "innovation",
    "creativity",
    "invention",
    "designThinking",
    "leadership",
  ],
  "Education & Learning": [
    "learning",
    "education",
    "eLearning",
    "onlineCourses",
    "studyTips",
    "selfImprovement",
    "professionalDevelopment",
  ],
  "Society & Politics": [
    "politics",
    "society",
    "humanRights",
    "activism",
    "community",
    "law",
    "sustainability",
    "ethics",
  ],
  "Finance & Economics": [
    "finance",
    "economics",
    "investing",
    "budgeting",
    "crypto",
    "stocks",
    "realEstate",
    "personalFinance",
  ],
  "Arts & Media": [
    "art",
    "literature",
    "music",
    "photography",
    "cinema",
    "theater",
    "media",
    "fashion",
  ],
  "Health & Lifestyle": [
    "health",
    "fitness",
    "nutrition",
    "mentalHealth",
    "wellness",
    "lifestyle",
    "selfCare",
    "travel",
  ],
  "Gaming & Entertainment": [
    "gaming",
    "videoGames",
    "entertainment",
    "movies",
    "tvShows",
    "comics",
    "anime",
    "boardGames",
  ],
  Miscellaneous: [
    "gardening",
    "pets",
    "foodie",
    "photography",
    "DIY",
    "scienceFiction",
    "history",
    "other",
  ],
};

export const ALL_TAGS = Object.values(TAGS_BY_CATEGORY).flat();
